version: '3.2'

services:

  backend:
    command: gunicorn --bind 0.0.0.0 --reload app:api
    volumes:
      - type: bind
        source: ./backend/
        target: /srv/app/

  frontend:
    command: npm start
    volumes:
      - type: bind
        source: ./frontend/
        target: /srv/app/
