version: '3.2'

services:

  backend:
    command: gunicorn --bind 0.0.0.0 --reload app:api
    volumes:
      - type: bind
        source: ./sapie-be/
        target: /srv/app/

  frontend:
    command: npm start
    volumes:
      - type: bind
        source: ./sapie-fe/
        target: /srv/app/

  sample:
    image: sapie-backend
    command: python sample.py
    restart: "no"
    environment:
      - SAPIE_ELASTICSEARCH=elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - type: bind
        source: ./sapie-be/
        target: /srv/app/
