TAGS = [
    'recruitment',
    'employment',
    'hiring',
    'job search',
    'careers',
    'job sites',
    'employment agencies',
    'job hiring',
    'job search websites',
    'jobs hiring',
    'job seekers',
    'recruit',
    'recruitment agencies',
    'recruiter',
    'recruiting',
    'job agency',
    'recruitment agency',
    'international recruitment agencies',
    'recruiting agency',
    'anxiety',
    'mindfulness',
    'calisthenics',
    'entrepreneurship',
    'intermittent fasting',
    'street workout',
    'productivity',
    'flexible dieting',
    'corporate wellness',
    'mobility training',
    'movement training',
    'corporate mindfulness',
    'bodyweight athletes',
    'video game streamers',
    'video game streaming teachers',
    'entrepreneur',
    'entrepreneurs',
    'young entrepreneurs',
    'women entrepreneurs',
    'global entrepreneur',
    'small entrepreneur',
    'international entrepreneur',
    'mindfulness meditation',
    'business entrepreneur',
    'small business entrepreneur',
    'live video game streaming',
    'playing video games for a living',
    'cheap flights',
    'all inclusive vacations',
    'vacation packages',
    'cuba vacations',
    'mexico vacations',
    'travel industry',
    'cheap tickets',
    'cheap flight tickets',
    'airline tickets',
    'cheap vacations',
    'cheap vacation packages',
    'cheap family vacations',
    'vacation deals',
    'vacation package deals',
    'great vacation deals',
    'last minute travel deals',
    'best travel deals',
    'best vacation deals',
    'best vacation spots',
    'trips to cuba',
    'vacation',
    'vacations',
    'vacation ideas',
    'vacation spots',
    'analytics',
    'seo',
    'inbound marketing',
    'digital agency',
    'serps',
    'rank tracking',
    'enterprise rank tracking',
    'content community',
    'retail & ecommerce',
    'search engine optimization',
    'digital marketing',
    'seo services',
    'seo company',
    'digital marketing agency',
    'web analytics',
    'advertising agency',
    'seo marketing',
    'marketing agency',
    'ad agency',
    'search marketing',
    'digital media agency',
    'local seo services',
    'seo service',
    'seo consulting services',
    'search engine marketing',
    'media agency',
    'search engine optimization consultant',
    'search engine optimization tools',
    'seo firm',
    'advertising firm',
    'digital marketing services',
    'digital advertising',
    'professional seo',
    'search engine optimization expert',
    'seo consulting',
    'seo strategy',
    'local seo',
    'seo agency',
    'ceo',
    'social media',
    'social  media marketing',
    'owner',
    'founder',
    'social media manager',
    'marketer',
    'digital marketer',
    'social media marketer',
    'android',
]
